<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <PackageId>ImGuiColorTextEditNetDalamud</PackageId>
        <Version>1.0.0</Version>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup>
        <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
        <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.xlcore/dalamud/Hooks/dev/</DalamudLibPath>
        <DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(HOME)/Library/Application Support/XIV on Mac/dalamud/Hooks/dev/</DalamudLibPath>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="Dalamud.Bindings.ImGui" HintPath="$(DalamudLibPath)\Dalamud.Bindings.ImGui.dll" Private="false"/>
        <Reference Include="Dalamud.Bindings.ImPlot" HintPath="$(DalamudLibPath)\Dalamud.Bindings.ImPlot.dll" Private="false"/>
        <Reference Include="Dalamud" HintPath="$(DalamudLibPath)Dalamud.dll" Private="false"/>
    </ItemGroup>
</Project>